easy_admin:
    entities:
        Message:
            class: App\Entity\Message
            list:
                fields:
                    - { property: 'is_enabled', type: 'toggle', label: 'Confirm' }
                    - id
                    - username
                    - text
                    - { property: 'picture', type: 'image', is_image_url: 'true', base_path: '/uploads/pictures/' }
                    - created_at
                    - user_ip
            form:
                fields:
                    - 'username'
                    - 'email'
                    - 'homepage'
                    - 'text'
                    - { property: 'picture', type: 'text' }

        User:
            class: App\Entity\User
            list:
                fields:
                    - id
                    - username
                    - email
                    - created_at
                    - { property: 'verifications', type: 'boolean'}
            form:
                fields:
                - 'username'
                - 'email'
                - { property: 'password', type: 'password' }
                - { property: 'roles', type: 'collection' }
                - 'created_at'
