swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }

#swiftmailer:
#    transport: 'smtp'
#    host:      'mail.myktm.ru'
#    username:  'exodus@myktm.ru'
#    password:  'boolean78'
#    port: 465