#index:
#    path: /
#    controller: App\Controller\DefaultController::index

message:
    path:     /{_locale}
    controller: App\Controller\MessageController::index
    requirements: {_locale: "%router.locales%"}
    defaults:  {_locale: '%locale%'}

create_message:
    path:     /{_locale}/message/create
    controller: App\Controller\MessageController::create
    requirements: {_locale: "%router.locales%"}
    defaults:  {_locale: '%locale%'}

update_message:
    path:     /{_locale}/message/update
    controller: App\Controller\MessageController::update
    requirements: {_locale: "%router.locales%"}
    defaults:  {_locale: '%locale%'}

single_message:
    path: /{_locale}/message/{message}
    controller: App\Controller\MessageController::message
    requirements: {_locale: "%router.locales%"}
    defaults:  {_locale: '%locale%'}

delete_message:
    path: /{_locale}/message/delete/{message}
    controller: App\Controller\MessageController::delete
    requirements: {_locale: "%router.locales%"}
    defaults:  {_locale: '%locale%'}

user_login:
    path: /{_locale}/login
    controller: App\Controller\SecurityController::login
    requirements: {_locale: "%router.locales%"}
    defaults:  {_locale: '%locale%'}

user_register:
    path: /{_locale}/register
    controller: App\Controller\SecurityController::registerAction
    requirements: {_locale: "%router.locales%"}
    defaults:  {_locale: '%locale%'}

user_logout:
    path: /{_locale}/logout
    controller: App\Controller\SecurityController::logout
    requirements: {_locale: "%router.locales%"}
    defaults:  {_locale: '%locale%'}

user_profile:
    path: /{_locale}/profile
    controller: App\Controller\SecurityController::profile
    requirements: {_locale: "%router.locales%"}
    defaults:  {_locale: '%locale%'}

comment_create_form:
    path: /{_locale}/comment/create/{message}
    controller: App\Controller\CommentController::create
    requirements: {_locale: "%router.locales%"}
    defaults:  {_locale: '%locale%'}